# Generated by Django 6.0.4 on 2026-05-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
