# Generated by Django 6.0.4 on 2026-05-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='likes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
